"""
Builds demo_warehouse.duckdb: a trimmed, free-tier-hostable copy of warehouse.duckdb
for the live public demo, alongside the full warehouse (which goes to GitHub Releases).

Design:
- All small dimension tables and season-aggregate tables (fact_player_*_rs/po,
  fact_team_*_rs/po) are copied IN FULL -- they're cheap and preserve full career
  history (all ~29 seasons) for archetypes, win shares, four factors, etc.
- dim_game and other per-game-but-small tables (fact_game_summary, fact_line_score,
  fact_officials, fact_other_stats, fact_inactive_players, dim_game_info,
  team_game_totals, qa_* tables) are copied IN FULL -- full game-browsing history.
- The handful of large row-level/event tables are trimmed to the 5 most recent
  seasons found in dim_game (2018-19 through 2022-23, which is the actual max
  season this dataset's play-by-play covers):
    fact_play_by_play, stint_players, fact_lineup_stints, fact_lineup_stints_clean,
    player_game_on, player_game_off, fact_player_boxscore_game,
    fact_player_boxscore_clutch
- fact_shot_chart is trimmed independently to ITS OWN 5 most recent seasons
  (SEASON_2), since shot-chart data actually extends to 2024-25 -- newer than
  the play-by-play/game dataset's 2022-23 ceiling.
- agg_lineup_stats has no season/game_id column at all, so it can't be filtered
  directly. It's regenerated by re-aggregating the TRIMMED fact_lineup_stints
  with the same formula the original table used (verified against real rows).
"""

import os
import time

import duckdb

SRC = "warehouse.duckdb"
DST = "demo_warehouse.duckdb"
N_RECENT_SEASONS = 5

if os.path.exists(DST):
    os.remove(DST)

t0 = time.time()
con = duckdb.connect(DST)
con.execute(f"ATTACH '{SRC}' AS src (READ_ONLY)")

all_tables = [r[0] for r in con.execute(
    "SELECT table_name FROM duckdb_tables() WHERE database_name = 'src'"
).fetchall()]
print(f"{len(all_tables)} tables in source warehouse")

recent_years = [r[0] for r in con.execute(
    "SELECT DISTINCT season_id % 10000 AS yr FROM src.dim_game ORDER BY yr DESC LIMIT ?",
    [N_RECENT_SEASONS],
).fetchall()]
print("Recent game-level season years (dim_game):", sorted(recent_years))

con.execute(f"""
    CREATE TEMP TABLE recent_game_ids AS
    SELECT DISTINCT game_id
    FROM src.dim_game
    WHERE (season_id % 10000) IN ({",".join(str(y) for y in recent_years)})
""")
n_recent_games = con.execute("SELECT COUNT(*) FROM recent_game_ids").fetchone()[0]
print("Games in recent-5-season window:", n_recent_games)

recent_shot_seasons = [r[0] for r in con.execute("""
    SELECT DISTINCT SEASON_2 FROM src.fact_shot_chart
    ORDER BY SEASON_2 DESC LIMIT ?
""", [N_RECENT_SEASONS]).fetchall()]
print("Recent shot-chart seasons:", recent_shot_seasons)

TRIM_BY_GAME_ID = [
    "fact_play_by_play",
    "stint_players",
    "fact_lineup_stints",
    "fact_lineup_stints_clean",
    "player_game_on",
    "player_game_off",
    "fact_player_boxscore_game",
    "fact_player_boxscore_clutch",
]
SPECIAL = {"agg_lineup_stats", "fact_shot_chart"}

for t in all_tables:
    if t in SPECIAL:
        continue
    if t in TRIM_BY_GAME_ID:
        con.execute(f"""
            CREATE TABLE {t} AS
            SELECT * FROM src.{t}
            WHERE game_id IN (SELECT game_id FROM recent_game_ids)
        """)
    else:
        con.execute(f"CREATE TABLE {t} AS SELECT * FROM src.{t}")
    n = con.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
    print(f"  {t}: {n} rows")

placeholders = ",".join(f"'{s}'" for s in recent_shot_seasons)
con.execute(f"""
    CREATE TABLE fact_shot_chart AS
    SELECT * FROM src.fact_shot_chart
    WHERE SEASON_2 IN ({placeholders})
""")
n = con.execute("SELECT COUNT(*) FROM fact_shot_chart").fetchone()[0]
print(f"  fact_shot_chart: {n} rows")

con.execute("""
    CREATE TABLE agg_lineup_stats AS
    SELECT
        team_id,
        lineup,
        COUNT(*) AS n_stints,
        SUM(seconds) AS total_seconds,
        SUM(points_for) AS points_for,
        SUM(points_against) AS points_against,
        SUM(points_for) - SUM(points_against) AS point_differential,
        SUM(possessions_est) AS possessions_est,
        SUM(points_for) / NULLIF(SUM(possessions_est), 0) * 100 AS off_rating_est,
        SUM(points_against) / NULLIF(SUM(possessions_est), 0) * 100 AS def_rating_est,
        (SUM(points_for) / NULLIF(SUM(possessions_est), 0) * 100)
            - (SUM(points_against) / NULLIF(SUM(possessions_est), 0) * 100) AS net_rating_est
    FROM fact_lineup_stints
    GROUP BY team_id, lineup
""")
n = con.execute("SELECT COUNT(*) FROM agg_lineup_stats").fetchone()[0]
print(f"  agg_lineup_stats (regenerated): {n} rows")

con.execute("DROP TABLE recent_game_ids")
con.execute("DETACH src")
con.close()

elapsed = time.time() - t0
size_bytes = os.path.getsize(DST)
print(f"\nDone in {elapsed:.1f}s")
print(f"{DST}: {size_bytes} bytes = {size_bytes/1e6:.1f} MB")
